function R_PQW_to_IJK = PQW_to_IJK(i, RAAN, AOP)
    % Author: Joshua Geiser
    % Inputs: Keplerian elements (km, rad, rad, rad, rad, rad)
    % Output: DCM from perifocal to inertial coordinates

    R_PQW_to_IJK = [cos(RAAN)*cos(AOP) - sin(RAAN)*cos(i)*sin(AOP), ...
                    -cos(RAAN)*sin(AOP) - sin(RAAN)*cos(i)*cos(AOP), ...
                    sin(RAAN)*sin(i); ...
                    sin(RAAN)*cos(AOP) + cos(RAAN)*cos(i)*sin(AOP), ...
                    -sin(RAAN)*sin(AOP) + cos(RAAN)*cos(i)*cos(AOP), ...
                    -cos(RAAN)*sin(i); ...
                    sin(i)*sin(AOP), ...
                    sin(i)*cos(AOP), ...
                    cos(i)];
end