function R = rotPQWtoIJK(Om,i,w)
RzOm = [cos(-Om),sin(-Om),0;...
        -sin(-Om),cos(-Om),0;...
        0,0,1];
Rxi = [1,0,0;...
       0,cos(-i),sin(-i);...
       0,-sin(-i),cos(-i)];
Rzw = [cos(-w),sin(-w),0;...
       -sin(-w),cos(-w),0;...
       0,0,1];
R = RzOm*Rxi*Rzw;
end