function A = eulerangle2dcm(e_vec)
    % convert the Eular Angle representation to DCM
    
    theta = e_vec(1); phi = e_vec(2); psi = e_vec(3);
    
    A = [cos(psi)*cos(phi) - cos(theta)*sin(psi)*sin(phi), ...
         cos(psi)*sin(phi) + cos(theta)*sin(psi)*cos(phi), ...
         sin(theta)*sin(psi); ...
         -sin(psi)*cos(phi) - cos(theta)*cos(psi)*sin(phi), ...
         -sin(psi)*sin(phi) + cos(theta)*cos(psi)*cos(phi), ...
         sin(theta)*cos(psi); ...
         sin(theta)*sin(phi), ...
         -sin(theta)*cos(phi), ...
         cos(theta)];
    
end