function dSdq = jacobian_st(S_ijk1,S_ijk2,S_ijk3,q1,q2,q3,q4)
%JACOBIAN_ST
%    DSDQ = JACOBIAN_ST(S_IJK1,S_IJK2,S_IJK3,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-May-2021 13:16:24

t2 = q1.*1.319517732905251;
t3 = q2.*1.319517732905251;
t4 = q3.*1.319517732905251;
t5 = q4.*1.319517732905251;
t6 = q1.*1.502954740685357;
t7 = q2.*1.502954740685357;
t8 = q3.*1.502954740685357;
t9 = q4.*1.502954740685357;
t10 = -t7;
t11 = -t9;
t12 = t3+t6;
t13 = t5+t8;
t14 = t2+t10;
t15 = t4+t11;
t16 = S_ijk1.*t12;
t17 = S_ijk2.*t12;
t18 = S_ijk3.*t12;
t19 = S_ijk1.*t13;
t20 = S_ijk2.*t13;
t21 = S_ijk3.*t13;
t22 = S_ijk1.*t14;
t23 = S_ijk2.*t14;
t24 = S_ijk3.*t14;
t25 = S_ijk1.*t15;
t26 = S_ijk2.*t15;
t27 = S_ijk3.*t15;
t28 = -t17;
t29 = -t20;
t30 = -t22;
t31 = -t24;
t32 = -t27;
t33 = t25+t29+t31;
t34 = t28+t30+t32;
dSdq = reshape([-t16-t21+t23,S_ijk1.*q3.*2.0-S_ijk2.*q4.*2.0-S_ijk3.*abs(q1).*sign(q1).*2.0,t34,t34,S_ijk1.*q4.*2.0+S_ijk2.*q3.*2.0-S_ijk3.*q2.*2.0,t16+t21-t23,-t18+t19+t26,S_ijk1.*q1.*2.0+S_ijk2.*q2.*2.0+S_ijk3.*q3.*2.0,t33,t33,S_ijk1.*q2.*2.0-S_ijk2.*q1.*2.0+S_ijk3.*q4.*2.0,t18-t19-t26],[3,4]);
